### ISSUE TITLE
`Minecraft启动流程与常见崩溃的解决/常见崩溃的解决（欢迎补充）.md` 的 `误用未混淆Mod` 一节有误

### ISSUE THREAD

**Issue by ZekerZhayard** [lovexyn0827/Discovering-Minecraft#2]
`java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)'`
这个方法是由 Forge 自己在 Minecraft 中添加的
https://github.com/MinecraftForge/MinecraftForge/blob/1.18.x/patches/minecraft/net/minecraft/server/level/DistanceManager.java.patch#L45
所以当然不会被重混淆

造成这个崩溃的原因是：用了旧版的 OptiFine；
因为 OptiFine 作用于 Minecraft 的方式是运行时整个类覆盖，所以当使用还没有适配新版 Forge 的 OptiFine 会把新版 Forge 对类的修改覆盖掉（这也是为什么 OptiFine 官网会注明推荐的 Forge 小版本号）

**Comment by lovexyn0827** [comment]
感谢反馈！个人对Forge开发了解较少，看来以后还得继续学习啊。
另外很抱歉这么晚才看到，目前已经在文中进行更正。
