### ISSUE TITLE
向量的“直接加入”操作和“加入”操作的区别未说明

### ISSUE THREAD

**Issue by H-J-Granger** [lovexyn0827/Discovering-Minecraft#5]
https://github.com/lovexyn0827/Discovering-Minecraft/blob/50696f0cb022f21d403fdf72152684dfa2c8039e/Minecraft%E5%AE%9E%E4%BD%93%E8%BF%90%E5%8A%A8%E7%A0%94%E7%A9%B6%E4%B8%8E%E5%BA%94%E7%94%A8/Chapter-5.md?plain=1#L83

“加到 v 中” 和 “直接加到 v 中”的区别是？

**Comment by lovexyn0827** [comment]
感谢反馈。
刚刚才确认了一下，其实这里是第二个“与h的积”是多余的。
这样看来，尽管在之前已经进行了多次检查，这篇文章应该仍还存在一定的细节性错误，高考后会再进行一次更彻底的更正。
