### ISSUE TITLE
LivingEntity运动机制第一节有误

### ISSUE THREAD

**Issue by xiaozi233** [lovexyn0827/Discovering-Minecraft#6]
https://github.com/lovexyn0827/Discovering-Minecraft/blob/1403a066ca83ee8c28e378e459814cade72b67ad/Minecraft%E5%AE%9E%E4%BD%93%E8%BF%90%E5%8A%A8%E7%A0%94%E7%A9%B6%E4%B8%8E%E5%BA%94%E7%94%A8/6-Chapter-6.md?plain=1#L92

个人看了下1.12的源码，应当是0.003m/gt
https://github.com/WangTingZheng/mcp940/blob/master/src/minecraft/net/minecraft/entity/EntityLivingBase.java#L2575-L2588
顺带一提，在1.8.9以前，这个数值为0.005m/gt，参见：
https://github.com/Marcelektro/MCP-919/blob/main/src/minecraft/net/minecraft/entity/EntityLivingBase.java#L1974-L1987

**Comment by lovexyn0827** [comment]
1.16+确实也是这个样子，应该还是当时的笔误[doge]

感谢指正！
